# Generated by Django 5.0.1 on 2024-03-24 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ("-published_date",)},
        ),
    ]
